<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\User;
use App\Models\Bus;

class BusSeeder extends Seeder
{
    public function run(): void
    {
        // --- People: Owners, Drivers, Conductors ---
        $people = [
            // Owners
            [
                'role' => 'owner',
                'name' => 'TransBrazzaville Ltd',
                'phone' => '+242065432100',
                'email' => 'contact@transbrazzaville.cg',
            ],
            [
                'role' => 'owner',
                'name' => 'Brazzaville Tours',
                'phone' => '+242065432101',
                'email' => 'info@brazzavilletours.cg',
            ],
            [
                'role' => 'owner',
                'name' => 'Congobus Express',
                'phone' => '+242065432102',
                'email' => 'support@congobus.cg',
            ],
            [
                'role' => 'owner',
                'name' => 'Les Voyages du Congo',
                'phone' => '+242065432103',
                'email' => 'hello@voyagesducongo.cg',
            ],

            // Drivers
            [
                'role' => 'driver',
                'name' => 'Michel Mavoungou',
                'phone' => '+242066123456',
                'license_no' => 'CG-DRV-4421',
            ],
            [
                'role' => 'driver',
                'name' => 'Arnaud Ndinga',
                'phone' => '+242066654321',
                'license_no' => 'CG-DRV-7812',
            ],
            [
                'role' => 'driver',
                'name' => 'Samantha Okombi',
                'phone' => '+242066112233',
                'license_no' => 'CG-DRV-3321',
            ],
            [
                'role' => 'driver',
                'name' => 'Emmanuel Moussavou',
                'phone' => '+242066445566',
                'license_no' => 'CG-DRV-9988',
            ],
            [
                'role' => 'driver',
                'name' => 'Bruno Loubou',
                'phone' => '+242066778899',
                'license_no' => 'CG-DRV-5566',
            ],
            [
                'role' => 'driver',
                'name' => 'Kevin Mabiala',
                'phone' => '+242066556677',
                'license_no' => 'CG-DRV-9900',
            ],
            [
                'role' => 'driver',
                'name' => 'Sylvie Moukila',
                'phone' => '+242066334455',
                'license_no' => 'CG-DRV-1010',
            ],

            // Conductor
            [
                'role' => 'conductor',
                'name' => 'Prince Ikouanga',
                'phone' => '+242067100001',
            ],
            [
                'role' => 'conductor',
                'name' => 'Clarisse Ndoutoume',
                'phone' => '+242067100002',
            ],
            [
                'role' => 'conductor',
                'name' => 'Boris Banzouzi',
                'phone' => '+242067100003',
            ],
            [
                'role' => 'conductor',
                'name' => 'Rita Massamba',
                'phone' => '+242067100004',
            ],
            [
                'role' => 'conductor',
                'name' => 'Hervé Louzolo',
                'phone' => '+242067100005',
            ],
            [
                'role' => 'conductor',
                'name' => 'Lucie Ngakala',
                'phone' => '+242067100006',
            ],
            [
                'role' => 'conductor',
                'name' => 'Alain Kifoueti',
                'phone' => '+242067100007',
            ],
            [
                'role' => 'conductor',
                'name' => 'Patricia Oko',
                'phone' => '+242067100008',
            ],
        ];

        $userMap = [];

        foreach ($people as $p) {
            $user = User::updateOrCreate(
                ['phone' => $p['phone']],
                [
                    'name'       => $p['name'],
                    'email'      => $p['email'] ?? null,
                    'phone'      => $p['phone'],
                    'role'       => $p['role'],
                    'license_no' => $p['license_no'] ?? null,
                    'password'   => bcrypt('Password123!'),
                ]
            );
            $userMap[$p['phone']] = $user->id;
        }

        // --- Buses ---
        // Added 'conductor_phone' to each record
        $buses = [
            [
                'plate' => 'CG-5412-BV',
                'capacity' => 30,
                'operator_phone' => '+242065432100',
                'driver_phone' => '+242066123456',
                'conductor_phone' => '+242067100001',
                'name' => 'Moukoukoulou Express',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Toyota Coaster',
                'year' => 2018,
                'mileage_km' => 120000,
                'last_service_date' => '2025-09-15',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-5412-22',
                'insurance_valid_until' => '2026-10-15',
            ],
            [
                'plate' => 'CG-8897-BV',
                'capacity' => 20,
                'operator_phone' => '+242065432100',
                'driver_phone' => '+242066654321',
                'conductor_phone' => '+242067100002',
                'name' => 'Poto-Poto Shuttle',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Hyundai County',
                'year' => 2020,
                'mileage_km' => 85000,
                'last_service_date' => '2025-09-28',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-8897-23',
                'insurance_valid_until' => '2026-10-20',
            ],
            [
                'plate' => 'CG-6723-BV',
                'capacity' => 40,
                'operator_phone' => '+242065432101',
                'driver_phone' => '+242066112233',
                'conductor_phone' => '+242067100003',
                'name' => 'Ouenze Flyer',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Mercedes Sprinter',
                'year' => 2019,
                'mileage_km' => 95000,
                'last_service_date' => '2025-09-10',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-6723-22',
                'insurance_valid_until' => '2026-09-30',
            ],
            [
                'plate' => 'CG-1155-BV',
                'capacity' => 15,
                'operator_phone' => '+242065432101',
                'driver_phone' => '+242066445566',
                'conductor_phone' => '+242067100004',
                'name' => 'Talangai Mini',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Isuzu Elf',
                'year' => 2021,
                'mileage_km' => 40000,
                'last_service_date' => '2025-09-25',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-1155-21',
                'insurance_valid_until' => '2026-09-25',
            ],
            [
                'plate' => 'CG-3344-BV',
                'capacity' => 50,
                'operator_phone' => '+242065432102',
                'driver_phone' => '+242066778899',
                'conductor_phone' => '+242067100005',
                'name' => 'Mfilou Express',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Scania K-series',
                'year' => 2017,
                'mileage_km' => 180000,
                'last_service_date' => '2025-09-05',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-3344-20',
                'insurance_valid_until' => '2026-08-30',
            ],
            [
                'plate' => 'CG-7788-BV',
                'capacity' => 18,
                'operator_phone' => '+242065432102',
                'driver_phone' => '+242066654321',
                'conductor_phone' => '+242067100006',
                'name' => 'Moungali Shuttle',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Fuso Rosa',
                'year' => 2019,
                'mileage_km' => 70000,
                'last_service_date' => '2025-09-20',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-7788-19',
                'insurance_valid_until' => '2026-09-20',
            ],
            [
                'plate' => 'CG-5566-BV',
                'capacity' => 35,
                'operator_phone' => '+242065432100',
                'driver_phone' => '+242066123456',
                'conductor_phone' => '+242067100007',
                'name' => 'Poto-Poto Express',
                'type' => 'coaster',
                'status' => 'maintenance',
                'model' => 'Volvo B9R',
                'year' => 2016,
                'mileage_km' => 220000,
                'last_service_date' => '2025-10-01',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-5566-18',
                'insurance_valid_until' => '2026-07-15',
            ],
            [
                'plate' => 'CG-9911-BV',
                'capacity' => 22,
                'operator_phone' => '+242065432101',
                'driver_phone' => '+242066112233',
                'conductor_phone' => '+242067100008',
                'name' => 'Marché Total Shuttle',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Toyota HiAce',
                'year' => 2021,
                'mileage_km' => 35000,
                'last_service_date' => '2025-09-30',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-9911-21',
                'insurance_valid_until' => '2026-09-30',
            ],

            // --- New realistic buses ---
            [
                'plate' => 'CG-2223-BV',
                'capacity' => 25,
                'operator_phone' => '+242065432103',
                'driver_phone' => '+242066556677',
                'conductor_phone' => '+242067100001',
                'name' => 'Bacongo Express',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Nissan Civilian',
                'year' => 2020,
                'mileage_km' => 68000,
                'last_service_date' => '2025-10-10',
                'insurance_provider' => 'SONAR Congo',
                'insurance_policy_number' => 'INS-2223-20',
                'insurance_valid_until' => '2026-10-10',
            ],
            [
                'plate' => 'CG-2234-BV',
                'capacity' => 45,
                'operator_phone' => '+242065432103',
                'driver_phone' => '+242066334455',
                'conductor_phone' => '+242067100002',
                'name' => 'Makélékélé Express',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Yutong ZK6108',
                'year' => 2022,
                'mileage_km' => 29000,
                'last_service_date' => '2025-09-27',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-2234-22',
                'insurance_valid_until' => '2026-09-27',
            ],
            [
                'plate' => 'CG-6711-BV',
                'capacity' => 55,
                'operator_phone' => '+242065432100',
                'driver_phone' => '+242066445566',
                'conductor_phone' => '+242067100003',
                'name' => 'Aéroport Express',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Volvo 9700',
                'year' => 2023,
                'mileage_km' => 15000,
                'last_service_date' => '2025-10-01',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-6711-23',
                'insurance_valid_until' => '2026-10-01',
            ],
            [
                'plate' => 'CG-9001-BV',
                'capacity' => 28,
                'operator_phone' => '+242065432102',
                'driver_phone' => '+242066556677',
                'conductor_phone' => '+242067100004',
                'name' => 'Kintélé Shuttle',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Toyota Coaster',
                'year' => 2020,
                'mileage_km' => 64000,
                'last_service_date' => '2025-09-18',
                'insurance_provider' => 'SONAR Congo',
                'insurance_policy_number' => 'INS-9001-20',
                'insurance_valid_until' => '2026-09-18',
            ],
            [
                'plate' => 'CG-3003-BV',
                'capacity' => 38,
                'operator_phone' => '+242065432101',
                'driver_phone' => '+242066334455',
                'conductor_phone' => '+242067100005',
                'name' => 'Plateau Express',
                'type' => 'coaster',
                'status' => 'maintenance',
                'model' => 'Mercedes Sprinter XL',
                'year' => 2018,
                'mileage_km' => 175000,
                'last_service_date' => '2025-09-10',
                'insurance_provider' => 'AXA Congo',
                'insurance_policy_number' => 'INS-3003-18',
                'insurance_valid_until' => '2026-09-10',
            ],
            [
                'plate' => 'CG-8200-BV',
                'capacity' => 20,
                'operator_phone' => '+242065432103',
                'driver_phone' => '+242066778899',
                'conductor_phone' => '+242067100006',
                'name' => 'Moungali Night Shuttle',
                'type' => 'hiace',
                'status' => 'active',
                'model' => 'Hyundai H350',
                'year' => 2022,
                'mileage_km' => 25000,
                'last_service_date' => '2025-10-05',
                'insurance_provider' => 'NSIA Congo',
                'insurance_policy_number' => 'INS-8200-22',
                'insurance_valid_until' => '2026-10-05',
            ],
            [
                'plate' => 'CG-9099-BV',
                'capacity' => 32,
                'operator_phone' => '+242065432102',
                'driver_phone' => '+242066334455',
                'conductor_phone' => '+242067100007',
                'name' => 'Talangai Express',
                'type' => 'coaster',
                'status' => 'active',
                'model' => 'Yutong Mini Coach',
                'year' => 2021,
                'mileage_km' => 41000,
                'last_service_date' => '2025-09-29',
                'insurance_provider' => 'SONAR Congo',
                'insurance_policy_number' => 'INS-9099-21',
                'insurance_valid_until' => '2026-09-29',
            ],
        ];

        foreach ($buses as $data) {
            Bus::updateOrCreate(
                ['plate' => $data['plate']],
                [
                    'plate'                  => $data['plate'],
                    'capacity'               => $data['capacity'],
                    'operator_id'            => $userMap[$data['operator_phone']] ?? null,
                    'assigned_driver_id'     => $userMap[$data['driver_phone']] ?? null,
                    'assigned_conductor_id'  => $userMap[$data['conductor_phone']] ?? null,
                    'name'                   => $data['name'],
                    'type'                   => $data['type'],
                    'status'                 => $data['status'],
                    'model'                  => $data['model'],
                    'year'                   => $data['year'],
                    'mileage_km'             => $data['mileage_km'],
                    'last_service_date'      => $data['last_service_date'],
                    'insurance_provider'     => $data['insurance_provider'],
                    'insurance_policy_number'=> $data['insurance_policy_number'],
                    'insurance_valid_until'  => $data['insurance_valid_until'],
                ]
            );
        }

        $this->command->info('✅ '.count($buses).' Buses seeded successfully!');
    }
}
